spring.application.name=auth-service
# Đổi cổng mặc định sang 8080 (hoặc tùy bạn)
server.port=8088

# Cấu hình Keycloak của bạn
keycloak.url=http://localhost:8010
keycloak.realm=Hethongphanquyen
keycloak.client-id=spring-boot-client
keycloak.client-secret=pLTHIdM1qy0Il6l5pD24TNqok0rJJE8b